### ISSUE TITLE
config/http: Support adding headers

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#998]
The HTTP transport's config integration needs an analog for the
[`http.AddHeader`][1] option.

Something like the following, using a `map[string]string`.

```
outbounds:
  myservice:
    http:
      url: ...
      headers:
        foo: bar
        baz: qux
```

An alternative that would allow multiple values for the same header (as
supported by the AddHeader API and the HTTP protocol itself) is using a slice
(`[]struct{Key, Value string}`).

```
headers:
  - name: foo
    value: bar
  - name: baz
    value: qux
```

It's a lot noisier to use but it's more compliant. It would also support
headers without values.

Thoughts? @yarpc/golang

[1]: https://godoc.org/go.uber.org/yarpc/transport/http#AddHeader
